# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Augenalarm
email: info@augenalarm.de
description: >- # this means to ignore newlines until "baseurl:"
  Augenalarm informiert über Netzhauterkrankungen und Operationen bei Netzhautlöchern und Netzhautablösungen aus der Sicht eines Betroffenen.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://augenalarm.de/

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# just-the-docs settings
back_to_top: true
back_to_top_text: "Nach Oben"

# External navigation links
nav_external_links:
  - title: Augenrat
    url: https://augenrat.de/
    hide_icon: false
    opens_in_new_tab: true
  - title: Gesundheitsinformation
    url: https://www.gesundheitsinformation.de/
    hide_icon: false
    opens_in_new_tab: true    
  # - title: Diagnose-Suche
  #   url: https://gesund.bund.de/icd-code-suche
  #   hide_icon: false
  #   opens_in_new_tab: true
  # - title: Medikamenten-Suche
  #   url: https://www.gelbe-liste.de/profi-suche
  #   hide_icon: false
  #   opens_in_new_tab: true
  # - title: Fachwort-Suche
  #   url: https://flexikon.doccheck.com/
  #   hide_icon: false
  #   opens_in_new_tab: true    

gh_edit_link: false
gh_edit_link_text: "Seite bearbeiten"
gh_edit_repository: "https://github.com/bennycode/augenalarm"
gh_edit_branch: "main"
# gh_edit_source: "docs"
gh_edit_view_mode: "tree"
